'use strict';
// Standalone portfolio examples. No original engine, API, real diary or full catalogue.
const fish=[{name:'Щука',group:'Пример карточки хищной рыбы',text:'В полном проекте карточка объединяет сведения о виде, способы ловли и связанные материалы. В демонстрации показана только структура карточки.'},{name:'Окунь',group:'Пример карточки хищной рыбы',text:'Одна карточка на вид, переходы к темам и понятная навигация. Биологическая база и источники в эту демоверсию не включены.'},{name:'Карась',group:'Пример карточки мирной рыбы',text:'Пример другого раздела каталога. Полная версия содержит дополнительные сведения; здесь можно проверить поиск и открытие карточек.'}];
function page(id){if(!document.getElementById(id)?.classList.contains('page'))return;document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==id);document.querySelectorAll('nav button').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.page===id)));location.hash=id;}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>page(b.dataset.page)));
window.addEventListener('hashchange',()=>page(location.hash.slice(1)||'home'));
function card(title,text){const el=document.createElement('article');el.className='card';const h=document.createElement('h2');h.textContent=title;const p=document.createElement('p');p.textContent=text;el.append(h,p);return el;}
function renderFish(){const q=document.getElementById('fish-search').value.trim().toLocaleLowerCase('ru');const rows=fish.filter(f=>f.name.toLocaleLowerCase('ru').includes(q));const host=document.getElementById('fish-list');host.replaceChildren();document.getElementById('empty').hidden=rows.length>0;document.getElementById('fish-detail').hidden=true;for(const f of rows){const c=card(f.name,f.group);const b=document.createElement('button');b.textContent='Открыть карточку';b.addEventListener('click',()=>{const d=document.getElementById('fish-detail');d.replaceChildren();const h=document.createElement('h2');h.textContent=f.name;const p=document.createElement('p');p.textContent=f.text;d.append(h,p);d.hidden=false;});c.append(b);host.append(c);}}
document.getElementById('fish-search').addEventListener('input',renderFish);renderFish();
function renderKit(){const boat=document.getElementById('kit-choice').value==='boat';const d=document.getElementById('kit-list');d.replaceChildren();const h=document.createElement('h2');h.textContent=boat?'Учебный комплект для лодки':'Учебный комплект для берега';const ul=document.createElement('ul');for(const t of boat?['Спасательный жилет','Комплект снастей','Запас воды и защита от погоды']:['Комплект снастей','Запас воды','Одежда по погоде']){const li=document.createElement('li');li.textContent=t;ul.append(li);}d.append(h,ul);}
document.getElementById('kit-choice').addEventListener('change',renderKit);renderKit();
document.getElementById('diary-list').append(card('Учебный выезд','Пример записи: проверили снасти, отметили впечатления от поездки.'));
document.getElementById('diary-form').addEventListener('submit',e=>{e.preventDefault();const title=document.getElementById('trip-title'),note=document.getElementById('trip-note');if(!title.value.trim())return;document.getElementById('diary-list').prepend(card(title.value.trim(),note.value.trim()||'Без заметки'));document.getElementById('diary-status').textContent='Учебная запись добавлена в текущую вкладку. После перезагрузки она исчезнет.';e.target.reset();});
page(location.hash.slice(1)||'home');
